server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:config-server}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    cloud:
      config:
        server:
          native:
            search-locations: ${CONFIG_SERVER_SEARCH_LOCATIONS}
